### ISSUE TITLE
Fix Typo

### ISSUE THREAD

**Issue by will76** [dannyroemhild/ransomware-fileext-list#32]
Simple fix that interferes when importing to FSRM

https://github.com/dannyroemhild/ransomware-fileext-list/blob/6f1e8428922550c8579fa395e1f539b41ceb9cd5/fileextlist.txt#L4794

**Comment by will76** [comment]
Well, I saw there are many entries like these. According to the OS, a file name can't contain: 

< (less than)
> (greater than)
: (colon - sometimes works, but is actually NTFS Alternate Data Streams)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)

**Comment by dannyroemhild** [comment]
Fixed with commit https://github.com/dannyroemhild/ransomware-fileext-list/commit/0c97a6ea7cda162e7d27a8fcbadb718136202df0 

sometimes there is
*.abc and abc.* ... in both cases the asterisk is used as a wildcard. And at least for me it is working in FSRM.

I could not find other special characters like the mentioned ones (<, >, :, ", /, \, |, ?) in the file. Please provide the exact line so I will check again.

Until the - thanks for the issue and have a great day
